FROM docker:latest

USER root

RUN apt-get update && apt-get install -y sudo

RUN addgroup docker
RUN useradd -ms /bin/bash -u 172cd4c3-b45d-47e0-ad18-f88ea0cd902e jenkins && usermod -aG docker jenkins

USER jenkins