version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://admin-bk:securepassword123@codesnippetdb.qy6om.mongodb.net/?retryWrites=true&w=majority&appName=CodeSnippetDB
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mongo-data:
